import { defineField, defineType } from "sanity";

export default defineType({
  name: "location",
  title: "Location",
  type: "document",
  fields: [
    defineField({ name: "locationName", title: "Location Name", type: "string", validation: (r) => r.required() }),
    defineField({ name: "slug", title: "Slug", type: "slug", options: { source: "locationName" }, validation: (r) => r.required() }),
    defineField({ name: "locationKey", title: "Location Key", type: "string", description: "Stable join key used by Team Members and other collections (usually same as slug).", validation: (r) => r.required() }),
    defineField({ name: "metaTitle", title: "Meta Title", type: "string" }),
    defineField({ name: "metaDescription", title: "Meta Description", type: "text" }),
    defineField({ name: "heroSubtext", title: "Hero Subtext", type: "text" }),
    defineField({ name: "heroImage", title: "Hero Image", type: "image", options: { hotspot: true } }),
    defineField({ name: "heroCtaLabel", title: "Hero CTA Label", type: "string" }),
    defineField({ name: "address", title: "Address", type: "string" }),
    defineField({ name: "city", title: "City", type: "string" }),
    defineField({ name: "postalCode", title: "Postal Code", type: "string" }),
    defineField({ name: "neighbourhoodsServed", title: "Neighbourhoods Served", type: "array", of: [{ type: "string" }] }),
    defineField({ name: "phoneCall", title: "Phone (Call)", type: "string" }),
    defineField({ name: "phoneText", title: "Phone (Text)", type: "string" }),
    defineField({ name: "email", title: "Email", type: "string" }),
    defineField({ name: "staffNotificationEmail", title: "Staff Notification Email", type: "string" }),
    defineField({
      name: "bookingMethod",
      title: "Booking Method",
      type: "string",
      options: { list: ["form", "phone"] },
      initialValue: "form",
    }),
    defineField({ name: "hours", title: "Hours", type: "array", of: [{ type: "string" }] }),
    defineField({ name: "googleMapsEmbedUrl", title: "Google Maps Embed URL", type: "url" }),
    defineField({ name: "geoLat", title: "Latitude", type: "number" }),
    defineField({ name: "geoLng", title: "Longitude", type: "number" }),
    defineField({ name: "teamHeading", title: "Team Heading", type: "string" }),
    defineField({ name: "teamIntro", title: "Team Intro", type: "text" }),
    defineField({ name: "listOrder", title: "List Order", type: "number", description: "Lower numbers appear first in location listings." }),
    defineField({
      name: "testimonials",
      title: "Testimonials",
      type: "array",
      of: [{ type: "reference", to: [{ type: "testimonial" }] }],
      validation: (r) => r.max(3),
    }),
  ],
  preview: {
    select: { title: "locationName", subtitle: "city" },
  },
});
